### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by malfynnction** [rmehner/bits-to-dead-trees#131]
Currently, bits-to-dead-trees doesn't care about the page's response code, it just takes a screenshot of the page. This can result in PDFs that contain only an error message.
It would be nice if there was an option to only generate a PDF for `200` responses, and return potential errors back to the caller so that our app can decide how to handle them.

**Comment by A5308Y** [comment]
I can't assign anyone to this issue, so I'll use the comment: I'm working on this currently.
